name: Deploy Python App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-app .

      - name: Stop old container
        run: |
          docker stop python-app || true
          docker rm python-app || true

      - name: Run new container
        run: docker run -d --name python-app python-app
